# Generated by Django 5.2.7 on 2025-10-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameyap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
